# Generated by Django 5.1.4 on 2025-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='media/profile_images/'),
        ),
    ]
