# Generated by Django 5.1.4 on 2025-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0004_detectedambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
