# Generated by Django 5.1.4 on 2025-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0005_webname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Webname',
            field=models.CharField(default='Smart Traffic System', max_length=100),
        ),
        migrations.AlterField(
            model_name='detectedambulance',
            name='img',
            field=models.ImageField(upload_to='detectiveAmbulance'),
        ),
    ]
