# Generated by Django 5.1.4 on 2025-10-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0006_delete_webname_userprofile_webname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedambulance',
            name='user',
        ),
    ]
