# Generated by Django 5.1.4 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0007_remove_detectedambulance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='detectiveIssues')),
                ('result', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectedAmbulance',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
