# Generated by Django 5.1.14 on 2025-11-11 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0009_bin_rewarditem_alter_detectedissues_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cnic',
            field=models.CharField(help_text='Format: XXXXX-XXXXXXX-X', max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity Bill'), ('gas', 'Gas Bill'), ('voucher', 'Voucher/Discount'), ('charity', 'Charity Donation')], max_length=20)),
                ('points_redeemed', models.IntegerField()),
                ('pkr_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='redemption_bills/')),
                ('voucher_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_type', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('charity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redemption Request',
                'verbose_name_plural': 'Redemption Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
