# Generated by Django 5.1.14 on 2025-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Light', '0010_alter_userprofile_cnic_redemptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for waste disposal', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cnic',
            field=models.CharField(blank=True, help_text='Format: XXXXX-XXXXXXX-X', max_length=15, null=True, unique=True),
        ),
    ]
